# Generated by Django 5.2.1 on 2025-10-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_per_bag',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price_per_paint',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
