# Generated by Django 5.2.1 on 2025-10-20 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticApp', '0005_remove_product_color_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='custom_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='package',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_choice',
            field=models.CharField(choices=[('Per_paint', 'Per_paint'), ('Per_bag', 'Per_bag')], default='Per_bag', max_length=30),
        ),
    ]
