# Generated by Django 5.2.1 on 2025-11-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticApp', '0010_order_reference_code_orderitem_package_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_choice',
            field=models.CharField(choices=[('Per_paint', 'Per_paint'), ('Per_bag', 'Per_bag')], default='Per_paint', max_length=30),
        ),
    ]
