# Generated by Django 5.2.1 on 2025-11-13 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staticApp', '0011_alter_product_price_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='old_price',
            new_name='old_per_bag',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='old_per_paint',
        ),
    ]
