# Generated by Django 5.2.1 on 2025-11-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticApp', '0012_rename_old_price_product_old_per_bag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='old_per_pack',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='old_per_tuba',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price_per_pack',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price_per_tuba',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_choice',
            field=models.CharField(choices=[('Per_paint', 'Per_paint'), ('Per_bag', 'Per_bag'), ('Per_tuba', 'Per_tuba'), ('Per_pack', 'Per_pack')], default='Per_paint', max_length=30),
        ),
    ]
